spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/issuemanager
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

auth:
  jwt:
    secret-key: tmp-key-hahahahahahahahaahahahahahahaha
    expiration-minutes: 30

